EVENT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('showcase.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcase/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'showcase'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.EventListView.as_view(), name='event-index'),
    path('create_event', views.EventCreateView.as_view(), name='create-event'),
    path('<int:pk>/update-event', views.EventUpdateView.as_view(), name='update-event'),
    path('<int:pk>/delete-event', views.EventDeleteView.as_view(), name='delete-event'),
    path('(?P<event_id>[0-9]+)/', views.detail, name='detail'),
    path('(?P<event_id>[0-9]+)/new-comment', views.create_comment, name='create-comment'),
    path('(?P<event_id>[0-9]+)/delete-comment/(?P<comment_id>[0-9]+)/', views.comment_delete, name='comment-delete'),
    path('<int:pk>/update-comment', views.CommentUpdateView.as_view(), name='comment_update'),
]

showcase/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

# Create your models here.


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=40)
    venue = models.CharField(max_length=35)
    time = models.TimeField()
    fee = models.CharField(max_length=4)
    date = models.DateField()
    description = models.TextField()
    contact = models.CharField(max_length=10)
    cover = models.FileField()

    def __str__(self):
        return self.event_name

    def get_absolute_url(self):
        return reverse('showcase:event-index')


class Comment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    email = models.EmailField()
    comment = models.TextField()
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('showcase:detail', args=[str(self.pk)])

showcase/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['email', 'comment']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

showcase/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Event, Comment
from .forms import CommentForm, UserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class EventListView(LoginRequiredMixin, ListView):
    model = Event
    context_object_name = 'events'


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    fields = ['event_name', 'venue', 'time', 'fee', 'date', 'description', 'contact', 'cover']

    def form_valid(self, form, **kwargs):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['event_name', 'venue', 'time', 'fee', 'date', 'description', 'contact', 'cover']

    def form_valid(self, form, **kwargs):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EventDeleteView(DeleteView):
    model = Event
    success_url = '/'


def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    comment = Comment.objects.all()
    return render(request, 'showcase/detail.html', {'event': event, 'comment': comment})


def create_comment(request, event_id):
    form = CommentForm(request.POST or None)
    event = get_object_or_404(Event, pk=event_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.event = event
        comment.save()
        return render(request, 'showcase/detail.html', {'event': event})
    return render(request, 'showcase/create_comment.html', {'form': form})


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('showcase:event-index')
    return render(request, 'registration/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('showcase:event-index')
    return render(request, 'registration/login.html')


def logout_user(request):
    logout(request)
    return redirect('showcase:login')


def comment_delete(request, event_id, comment_id):
    event = get_object_or_404(Event, pk=event_id)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return render(request, 'showcase/detail.html', {'event':event})


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ['email', 'comment']
    template_name = 'showcase/update_comment.html'

showcase/templates/showcase/base.html
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'showcase/style.css' %}" type="text/css">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{% url 'showcase:event-index' %}">Event</a>
    <ul class="navbar-nav mr-auto ml-5">
        <li class="nav-item">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
        </li>
    </ul>
      <ul class="navbar-nav navbar-right">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'showcase:create-event' %}"><i class="fas fa-plus-square"></i>&nbsp Add Event<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'showcase:logout' %}"><i class="fas fa-sign-out-alt"></i>&nbsp Logout</a>
      </li>
    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

showcase/templates/showcase/detail.html
{% extends 'showcase/base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <img src="{{event.cover.url}}" style="width:100%; height:50%; padding:10px;">
            <div class="card card-body">
            <h4>{{event.event_name}}</h4>
                <p>{{event.venue}}</p>
                <p>{{event.time}}</p>
                <p>{{event.date}}</p>
                <p>{{event.fee}}</p>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card card-header">
                <h5 style="color:white;">Description</h5>
            </div>
            <div class="card card-body">
                <p>{{event.description}}</p>
            </div>

            <div class="card card-header">
                <h5 style="color:white;">Comments</h5>
            </div>
            <a href="{% url 'showcase:create-comment' event.id %}"><button class="btn btn-primary">Leave a comment</button></a>
                {% if event.comment_set %}
                {% for comment in event.comment_set.all %}

                <div class="card card-footer">
                    <p style="color:red;"> {{ comment.email }}</p><br>
                    <p style="color:white;">{{ comment.comment }}</p>

                    <a class="btn btn-danger" style="width:10%; float:right;" href="{% url 'showcase:comment-delete' event.id comment.id%}"><i class="fas fa-trash"></i></a>
                    <a class="btn btn-primary" style="width:10%; float:right;" href="{% url 'showcase:comment_update' comment.id %}"><i class="fas fa-edit"></i></a>
                    
                </div>
                {% endfor %}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}

showcase/templates/showcase/event_confirm_delete.html
{% extends 'showcase/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h4>Confirm Delete</h4>
            <form method="post" class="form-horizontal">
                {% csrf_token %}
                <p>Are you sure you want to delete this event?</p>
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                <a href="{% url 'showcase:event-index' %}" class="btn btn-primary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

showcase/templates/showcase/event_form.html
{% extends 'showcase/base.html' %}
{% block title %}{% if object %}Update Event{% else %}Create Event {% endif %}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="panel panel-primary">
                <h4>{% if object %} Update Event {% else %}Create Event{% endif %}</h4>
                <hr>
                <form method="post" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

showcase/templates/showcase/event_list.html
{% extends 'showcase/base.html' %}
{% block title %}Events{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if events %}
         {% for event in events %}
            <div class="col-sm-3">
            <div class="card my-2">
                <a href="{% url 'showcase:detail' event.id %}" ><img src="{{event.cover.url}}" class="img img-responsive" style="height:250px; width:250px;" alt=""></a>
                <h6 style="text-align:center;">{{event.event_name}}</h6>


            </div>
            <div class="card card-body" style="text-align:justify; ">
                <p>{{event.venue}}</p>
                <p>{{event.time}}</p>
                <p>{{event.date}}</p>
                <a href="{% url 'showcase:update-event' event.id %}" class="btn btn-primary"><i class="fas fa-edit"></i></a>&nbsp; <a href="{% url 'showcase:delete-event' event.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>

            </div>
            </div>
         {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

showcase/templates/showcase/update_comment.html
{% extends 'showcase/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Comment {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-header">
                <h4>Update comment</h4>
            </div>
            <div class="card card-body">
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group">
                        <button class="btn btn-success" style="width:100%;">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}